In [1]:
import numpy as np

In [2]:
list1 = [1, 2, 3]
a = np.array(list1)
a

array([1, 2, 3])

In [3]:
print(a.shape)

(3,)


In [4]:
# 2차원 구조
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(b.shape)

(2, 4)


In [5]:
print(b[0,0])

1


In [6]:
print(type(b))

<class 'numpy.ndarray'>


In [7]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
# 1행 2열
b[1, 2]

np.int64(7)

In [9]:
a = np.array([1, 2.3, 3, 4])
print(a)

[1.  2.3 3.  4. ]


In [10]:
a = np.array([1, '2', '3', 4])
print(a)

['1' '2' '3' '4']


In [11]:
a = np.array([1, 2, '3', 4])
print(a)

['1' '2' '3' '4']


In [12]:
# 1차원 구조
a1 = np.array([1, 2, 3, 4, 5])
# 2차원 구조
a2 = np.array([[1, 2, 3, 4,], [1, 2, 3, 4]])
# 3차원 구조
a3 = np.array([[[1, 2, 3], [1, 2, 3]],
             [[1, 2, 3], [1, 2, 3]],
             [[1, 2, 3], [1, 2, 3]]])

In [13]:
a1

array([1, 2, 3, 4, 5])

In [14]:
a2

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [15]:
a3 

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [16]:
# rank 구하기
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [17]:
# 구조 보여주기
print(a1.shape)
print(a2.shape)
print(a3.shape)

(5,)
(2, 4)
(3, 2, 3)


## numpy 배열 관련 함수

### zeros() : 값을 0으로 채워서 numpy 배열을 만드는 함수

In [18]:
a = np.zeros((3), dtype='int64')
print(a)

[0 0 0]


In [19]:
a = np.zeros((2, 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [20]:
a = np.zeros((2, 2, 2), dtype='int64')
print(a)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


### ones() : 값을 1로 채워서 numpy 배열을 만드는 함수

In [21]:
a = np.ones((3), dtype='int64')
print(a)

[1 1 1]


In [22]:
a = np.ones((3))
print(a)

[1. 1. 1.]


In [23]:
a = np.ones((2, 3), dtype='int64')
print(a)

[[1 1 1]
 [1 1 1]]


### full() : 원하는 값으로 채워서 numpy 배열을 만드는 함수

In [24]:
a = np.full((3), 5, dtype='int64')
print(a)

[5 5 5]


In [25]:
a = np.full((3), 10, dtype='int64')
print(a)

[10 10 10]


In [26]:
a = np.full((2, 3), 5, dtype='int64')
print(a)

[[5 5 5]
 [5 5 5]]


### eye() : 값이 0인 2차원 배열을 생성하는 함수 (이때, 대각선은 1로 채워진다)

In [27]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### arrange() : 범위를 지정하여 배열을 생성하는 함수

In [28]:
a = range(0, 10, 2)
a

range(0, 10, 2)

In [29]:
print(list(a))

[0, 2, 4, 6, 8]


In [30]:
print(np.array(list(a)))

[0 2 4 6 8]


In [31]:
a = np.arange(0, 10, 2)
print(a)

[0 2 4 6 8]


In [32]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


### reshape() : 배열의 구조를 변경하는 함수

In [33]:
a = np.array(range(12)).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
a = np.arange(12).reshape((3,-1))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
a = np.arange(12).reshape((6,-1))
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [37]:
a = np.arange(12).reshape((-1, 3))
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## numpy slicing(슬라이싱)

In [38]:
lst = [[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
# [행 슬라이싱, 열 슬라이싱]
a = arr[0:2, 0:2]
a

array([[1, 2],
       [4, 5]])

In [40]:
a = arr[1:, 1:]
a

array([[5, 6],
       [8, 9]])

In [41]:
a = [0,1,2,3]
b= np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])

In [42]:
print(a[1:4:2])

[1, 3]


In [43]:
a = np.array([0,1,2,3])
b= np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])

In [44]:
print(a[1:4:2])

[1 3]


In [45]:
print(a[::-1])

[3 2 1 0]


In [46]:
print(b[0][1])

1


In [47]:
print(b[0,1])

1


In [48]:
print(b[:2])

[[0 1 2 3]
 [4 5 6 7]]


In [49]:
print(b[:, 0])

[0 4 8]


In [50]:
print(b[0, :])

[0 1 2 3]


In [51]:
print(b[[0,2], :])

[[ 0  1  2  3]
 [ 8  9 10 11]]


In [52]:
print(b[[2,0], :])

[[ 8  9 10 11]
 [ 0  1  2  3]]


In [53]:
b_5 = b > 5
print(b_5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [54]:
# True만 추출
print(b[b_5])

[ 6  7  8  9 10 11]


In [55]:
# numpy 정수 indexing
print(b[[0, 1, 2], [1, 2, 0]])

[1 6 8]


In [56]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Broadcasting

In [57]:
a = np.array([0,1,2,3])
c = np.arange(4)
print(a)
print('---------')
print(c)

[0 1 2 3]
---------
[0 1 2 3]


In [58]:
print(c + 1)

[1 2 3 4]


In [59]:
print(a + c)

[0 2 4 6]


In [60]:
d = np.zeros((2,2,4))
print(d)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [61]:
print(d + c)

[[[0. 1. 2. 3.]
  [0. 1. 2. 3.]]

 [[0. 1. 2. 3.]
  [0. 1. 2. 3.]]]


In [62]:
a = [0, 1, 2, 3]
b = [0, 1, 2, 3]
print(a + b)

[0, 1, 2, 3, 0, 1, 2, 3]


In [63]:
x = []
for i, j in zip(a, b):
    x.append(i + j)

print(x)

[0, 2, 4, 6]


In [64]:
a = np.array([0,1,2,3])
c = np.arange(4)
print(a)
print('---------')
print(c)

[0 1 2 3]
---------
[0 1 2 3]


In [65]:
print(a + c)

[0 2 4 6]


### shape 변환

In [66]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
np.split(a, 2, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [68]:
# 1이 기준점에 해당
# [:1] 0-1행 : 0행 분리
# [1:3] 1-3행 : 1행, 2헹 분리
# [3:] 3행 : 3행 분리
np.split(a, (1, 3))

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [69]:
np.split(a, 2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [70]:
np.split(a, (1, 3), axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [71]:
# split(axis=1)
splite1, splite2 = np.hsplit(a, 2)

In [72]:
print('splite1'); print(splite1)

splite1
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [73]:
print('splite2'); print(splite2)

splite2
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [74]:
# split(axis=0)
splite1, splite2 = np.vsplit(a, 2)

In [75]:
print('splite1'); print(splite1)

splite1
[[0 1 2 3]
 [4 5 6 7]]


In [76]:
print('splite2'); print(splite2)

splite2
[[ 8  9 10 11]
 [12 13 14 15]]


### stack 연산

In [77]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
stack0 = np.stack((a,a))
print(stack0.shape)

(2, 4, 4)


In [79]:
print(stack0)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]


In [80]:
stack1 = np.stack((a,a), axis=1)
print(stack1.shape)

(4, 2, 4)


In [81]:
print(stack1)

[[[ 0  1  2  3]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [12 13 14 15]]]


In [82]:
# 2차원 구조
print(np.vstack((a,a)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [83]:
# 2차원 구조
print(np.hstack((a,a)))

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]
 [12 13 14 15 12 13 14 15]]


In [84]:
a = np.arange(9).reshape(3,3)
b = 2 * a
print(a)
print('------------')
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [85]:
print(np.hstack((a,b)))

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [86]:
print(np.concatenate((a,b), axis=1))

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [87]:
print(np.vstack((a,b)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [88]:
print(np.concatenate((a,b), axis=0))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


### flatten 연산 / ravel 연산 : 2차원 구조를 1차원 구조로 변경하는 함수

In [89]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
# a와 b는 별개
b = a.flatten()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [91]:
# a와 c는 연결
c = a.ravel()
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [92]:
b[0] = 100
print(b)
print(a)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [93]:
c[0] = 100
print(c)
print(a)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]


## numpy 배열 연산

In [94]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [95]:
print(a+b)

[5 7 9]


In [96]:
print(np.add(a, b))

[5 7 9]


In [97]:
print(a*b)

[ 4 10 18]


In [98]:
print(np.multiply(a, b))

[ 4 10 18]


In [99]:
## 행렬 곱 연산
lst1 = [[1, 2], [3, 4]]
lst2 = [[1, 2], [3, 4]]
a = np.array(lst1)
b = np.array(lst2)
c = np.dot(a, b)
print(c)

[[ 7 10]
 [15 22]]


In [100]:
a = np.array([[1, 2], [3, 4]])
s = np.sum(a, axis=0)
print(s)

[4 6]


In [101]:
s = np.sum(a, axis=1)
print(s)

[3 7]


In [102]:
# 각 배열 요소들을 모두 곱함
s = np.prod(a)
print(s)

24


In [103]:
s = np.prod(a, axis = 0)
print(s)

[3 8]


In [104]:
s = np.prod(a, axis = 1)
print(s)

[ 2 12]


## random 서브 패키지

In [106]:
np.random.seed(0)
print(np.random.rand(5))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


In [109]:
print(np.random.rand(5))

[0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]


In [113]:
x = np.arange(10)
print(x)
print('-----------------')
np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
-----------------
[0 5 3 2 9 7 1 4 8 6]


In [115]:
z = np.random.choice(5, 3, replace=False)
print(z)

[0 3 2]


In [117]:
z = np.random.choice(10, 20, replace=True)
print(z)

[1 5 9 3 0 5 0 1 2 4 2 0 3 2 0 7 5 9 0 2]


In [118]:
z = np.random.choice(5, 50, p=[0.1, 0, 0.3, 0.6, 0])
print(z)

[3 2 3 3 3 3 2 3 3 3 3 3 0 2 0 3 3 3 2 2 3 2 2 2 3 3 2 3 3 2 3 3 3 3 3 3 2
 3 3 3 2 2 3 3 3 3 2 2 3 3]


In [119]:
x = np.random.randint(5, size=5)
print(x)

[0 0 1 2 0]


In [120]:
x = np.random.randint(1, 100, size=5)
print(x)

[55 80 12 39 94]


In [126]:
a = [5, 1, 7, 7, 2, 3, 5, 1, 2, 7, 7]
x = np.unique(a)
print(x)

[1 2 3 5 7]


In [127]:
x, cnt = np.unique(a, return_counts=True)
print(x, cnt, sep=',')

[1 2 3 5 7],[2 2 1 2 4]


In [132]:
x = [18, 5, 10, 23, 19, -8, 10, 0, 6, 2]
print(len(x))
print(sum(x))
print(np.size(x))
print(np.sum(x))
print(np.mean(x))
print(np.var(x))
print(np.std(x))
print(np.max(x))
print(np.min(x))
print(np.median(x))
print(np.sort(x))

10
85
10
85
8.5
82.05
9.058145505565696
23
-8
8.0
[-8  0  2  5  6 10 10 18 19 23]
